"""""""""""
" PLUGINS "
"""""""""""
" {{{

" You can install vim-plug by running in your shell:
"
" curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
"    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
"
"  Ex command to install the plugins listed here:
" :PlugUpdate

call plug#begin()
    Plug 'tpope/vim-surround'
call plug#end()

" }}}

"""""""""""""""""
" USER COMMANDS "
"""""""""""""""""
" {{{

command -nargs=+ Mkdir !mkdir -p <args>

command -nargs=+ -complete=dir Rmdir call general#RemoveDirectories(<f-args>)

command Syn call general#Syn()

" }}}

""""""""""""""""
" AUTOCOMMANDS "
""""""""""""""""
" {{{

" Autocommand group deleting all its autocommands each time this file is sourced.
augroup vimrc
    autocmd!
augroup END

autocmd vimrc BufWrite * call general#DeleteTrailingWS()

autocmd vimrc BufEnter $MYVIMRC setlocal foldmethod=marker

" }}}

""""""""""""
" MAPPINGS "
""""""""""""
" {{{

nmap <space> <nop>
let mapleader = "\<space>"
let maplocalleader = "\<space>"

" Disable the arrow keys (use hjkl instead, respectively)
nmap <left> <nop>
nmap <down> <nop>
nmap <up> <nop>
nmap <right> <nop>

" Create a new tab
nnoremap <leader>t <cmd>tabnew<cr>
" Move to the next buffer
nnoremap <leader>nb <cmd>bnext<cr>
" Move to the next tab
nnoremap <leader>nt gt
" Delete the current buffer without closing the current window
nnoremap <leader>dd <cmd>bprevious <bar> bdelete! #<cr>

" Y behave conceptually like D or C
nnoremap Y y$
" Open the vimrc in a new window
nnoremap <f5> <cmd>vsplit $MYVIMRC<cr>
" Reload the vimrc directly from Vim
nnoremap <f6> <cmd>source $MYVIMRC<cr>

" Move from window to window using CTRL-{direction} instead of CTRL-w {direction}
nnoremap <c-h> <c-w>h
nnoremap <c-j> <c-w>j
nnoremap <c-k> <c-w>k
nnoremap <c-l> <c-w>l

" Toggle relative line numbers
nnoremap <c-n> <cmd>set relativenumber!<cr>
inoremap <c-n> <cmd>set relativenumber!<cr>

" }}}

"""""""""""""""
" STATUS LINE "
"""""""""""""""
" {{{

let &statusline='%r'                               "Read Only flag
let &statusline.=' %t'                             "Filename
let &statusline.=' %m'                             "Modified Flag
let &statusline.=' Buf %n'                         "Buffer Number
let &statusline.=' %{general#WordCount()}'         "Word count

set tabline=%!general#TabLine()

" }}}

"""""""""""
" OPTIONS "
"""""""""""
" {{{

" Can copy-paste more easily from and to Vim
set clipboard+=unnamedplus

" No compatibility with Vi
set nocompatible

" Display absolute line numbers
set number

" Enhanced completion in command-line mode
set wildmenu

" Syntax highlighting
syntax on

" Enable filetype, indentation, plugin
filetype plugin indent on

" Always display the status bar
set laststatus=2

" Allow hidding buffers
set hidden

" Use case insensitive search, except when using uppercases
set ignorecase
set smartcase

" Highlight the matches after a search
set hlsearch

" Disable the swap file for all buffers
" See :help swap-file
set noswapfile

" Add directory of the current file "."
" Add all directories and sub-directories of the global working directory "**"
set path=.,**,,

let &grepprg='grep -n $*'
" If ripgrep is installed, use it for :grep and :grepadd
if executable('rg')
    let &grepprg='rg --vimgrep --smart-case $*'
endif

" Save undo trees in files
set undofile
set undolevels=10000 " Maximum number of changes that can be undone (default 1000)

" }}}
